apiVersion: v1
appVersion: 2.14.17.0-b6
version: 2.14.17
home: https://www.yugabyte.com
description: YugaWare is YugaByte Database's Orchestration and Management console.
name: yugaware
icon: https://avatars0.githubusercontent.com/u/17074854?s=200&v=4
maintainers:
- name: Ram Sri
  email: ram@yugabyte.com
- name: Arnav Agarwal
  email: arnav@yugabyte.com
