{{- if and .Values.serviceMonitor.enabled .Values.serviceMonitor.master.enabled }}
{{- $appLabelArgs := dict "label" "yb-master" "root" . -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "yugabyte.fullname" . }}-yb-master
  labels:
    {{- include "yugabyte.applabel" ($appLabelArgs) | indent 4 }}
    {{- include "yugabyte.labels" . | indent 4 }}
    {{- with .Values.serviceMonitor.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  jobLabel: "release"
  selector:
    matchLabels:
      {{- if .Values.oldNamingStyle }}
      app: "yb-master"
      {{- else }}
      app.kubernetes.io/name: "yb-master"
      {{- end }}
      release: {{ .Release.Name | quote }}
      service-type: "headless"
  endpoints:

  {{- with .Values.serviceMonitor.master }}
  {{- if .enabled }}
  - port: {{ .port }}
    path: {{ .path }}
    {{- if .interval }}
    interval: {{ .interval }}
    {{- else }}
    interval: {{ $.Values.serviceMonitor.interval }}
    {{- end }}
    relabelings:
    - targetLabel: "group"
      replacement: "yb-master"
    - targetLabel: "export_type"
      replacement: "master_export"
    - targetLabel: "node_prefix"
      replacement: {{ $.Release.Name | quote }}
    metricRelabelings:
    {{- toYaml $.Values.serviceMonitor.commonMetricRelabelings | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
