{{- if and .Values.kubeStateMetrics.install (not .Values.kubeStateMetrics.customEndpoint) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ .Release.Name }}-yugaware-ksm
    chart: {{ template "yugaware.chart" . }}
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}-ksm
{{- end -}}