apiVersion: v1
name: yugabyte
version: 2.15.2
appVersion: 2.15.2.0-b87
home: https://www.yugabyte.com
description: YugabyteDB is the high-performance distributed SQL database for building global, internet-scale apps.
icon: https://avatars0.githubusercontent.com/u/17074854?s=200&v=4
sources:
- https://github.com/yugabyte/yugabyte-db
maintainers:
- name: Sanketh Indarapu
  email: sanketh@yugabyte.com
- name: Govardhan Reddy Jalla
  email: gjalla@yugabyte.com
