# yugabyte-helm-operations role has set of permissions required to
# install, upgrade, delete the yugabyte chart.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yugabyte-helm-operations
rules:
- apiGroups:
  - "policy"
  resources:
  - "poddisruptionbudgets"
  verbs:
  - "get"
  - "create"
  - "delete"
  - "patch"
- apiGroups:
  - ""
  resources:
  - "services"
  verbs:
  - "get"
  - "delete"
  - "create"
  - "patch"
- apiGroups:
  - "apps"
  resources:
  - "statefulsets"
  verbs:
  - "get"
  - "list"
  - "delete"
  - "create"
  - "patch"
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "create"
  - "list"                      # needed by Helm
  - "get"
  - "delete"
  - "update"                    # needed by Helm
  - "patch"
- apiGroups:
  - "cert-manager.io"
  resources:
  - "certificates"
  verbs:
  - "create"
  - "delete"
  - "get"
  - "patch"
- apiGroups:
  - ""
  resources:
  - "configmaps"
  verbs:
  - "get"
  - "create"
  - "patch"
  - "delete"
- apiGroups:
  - "multicluster.x-k8s.io"
  resources:
  - "serviceexports"
  verbs:
  - "get"
  - "create"
  - "patch"
  - "delete"
- apiGroups:
  - "net.gke.io"
  resources:
  - "serviceexports"
  verbs:
  - "get"
  - "create"
  - "patch"
  - "delete"
## We don't use ServiceMonitor in platform
# - apiGroups:
#   - "monitoring.coreos.com"
#   resources:
#   - "servicemonitors"
#   verbs:
#   - "get"
#   - "delete"
#   - "create"
#   - "patch"
---

# yugabyte-management role has set of permissions required by
# platform software to manage YugabyteDB universes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yugabyte-management
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  verbs:
  - "delete"
  - "create"
  - "patch"
  - "get"
  - "list"
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "get"                       # required for single pod
  - "list"                      # required for get pods
  - "delete"                    # required by rolling restart
- apiGroups:
  - ""
  resources:
  - "services"
  verbs:
  - "get"
  - "list"                      # required for label selectors
- apiGroups:
  - ""
  resources:
  - "persistentvolumeclaims"
  verbs:
  - "get"                       # required for pvc expansion
  - "patch"
  - "list"                      # required for label selectors
  - "delete"
- apiGroups:
  - ""
  resources:
  - "pods/exec"
  verbs:
  - "create"                      # required for exec and cp
- apiGroups:
  - "apps"
  resources:
  - "statefulsets/scale"
  verbs:
  - "patch"                     # required for scale command
- apiGroups:
  - ""
  resources:
  - "events"
  verbs:
  - "list"
# required to scrape metrics from external clusters
# required to validate zones during provider creation
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - get
  - watch
# required to scrape metrics from external clusters
- apiGroups:
  - ""
  resources:
  - nodes/proxy
  verbs:
  - get
# required to validate storage class during provider creation and
# volume expansion
- apiGroups:
  - "storage.k8s.io"
  resources:
  - "storageclasses"
  verbs:
  - "get"
# required to validate existance of issuer during provider creation
- apiGroups:
  - "cert-manager.io"
  resources:
  - "issuers"
  - "clusterissuers"
  verbs:
  - "get"
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: yugabyte-helm-operations
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: yugabyte-helm-operations
subjects:
  - kind: ServiceAccount
    name: yugabyte-platform-universe-management
    namespace: <SA_NAMESPACE>
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: yugabyte-management
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: yugabyte-management
subjects:
  - kind: ServiceAccount
    name: yugabyte-platform-universe-management
    namespace: <SA_NAMESPACE>
---
