{{- if and .Values.perfAdvisor.enabled .Values.tls.enabled }}

{{- if not .Values.tls.certManager.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-perf-advisor-tls-pem
  labels:
    app: {{ template "yugaware.name" . }}
    chart: {{ template "yugaware.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.commonLabels }}
{{ include "yugaware.commonLabels" . | indent 4 }}
{{- end }}
type: Opaque
data:
{{- include "yugaware.getOrCreatePerfAdvisorServerPem" (dict "Namespace" .Release.Namespace "Root" . "Name" (printf "%s%s" .Release.Name "-perf-advisor-tls-pem")) | nindent 3 }}
{{- end }}

{{- if .Values.tls.certManager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-perf-advisor-tls
  namespace: {{ .Release.Namespace }}
spec:
  isCA: false
  commonName: {{ .Values.tls.hostname }}
  secretName: {{ .Release.Name }}-perf-advisor-tls-cert
  secretTemplate:
    labels:
      app: {{ template "yugaware.name" . }}
      chart: {{ template "yugaware.chart" . }}
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
{{- if .Values.commonLabels }}
{{ include "yugaware.commonLabels" . | indent 6 }}
{{- end }}
  duration: {{ .Values.tls.certManager.configuration.duration | quote }}
  renewBefore: {{ .Values.tls.certManager.configuration.renewBefore | quote }}
  privateKey:
    algorithm: {{ .Values.tls.certManager.configuration.algorithm | quote }}
    encoding: PKCS8
    size: {{ .Values.tls.certManager.configuration.keySize }}
    rotationPolicy: Always
  issuerRef:
    name: {{ .Values.tls.certManager.genSelfsigned | ternary (printf "%s%s" .Release.Name "-yugaware-ca-issuer") (.Values.tls.certManager.useClusterIssuer | ternary .Values.tls.certManager.clusterIssuer .Values.tls.certManager.issuer) }}
    {{- if .Values.tls.certManager.useClusterIssuer }}
    kind: ClusterIssuer
    {{- else }}
    kind: Issuer
    {{- end }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-perf-advisor-export-certs
  labels:
    app: {{ .Release.Name }}-perf-advisor
    chart: {{ template "yugaware.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.commonLabels }}
{{ include "yugaware.commonLabels" . | indent 4 }}
{{- end }}
data:
  export-certs.sh: |
    #!/bin/bash
    set -x -o errexit

    rm -f /opt/yugabyte/perf-advisor/certs/tls.p12

    openssl pkcs12 -export -inkey /opt/yugabyte/perf-advisor/pem-certs/tls.key \
    -in /opt/yugabyte/perf-advisor/pem-certs/tls.crt \
    -out /opt/yugabyte/perf-advisor/certs/tls.p12 \
    -password pass:${KEYSTORE_PASSWORD}

{{- end }}
