{{- if .Values.perfAdvisor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-perf-advisor-service
  labels:
    app: {{ .Release.Name }}-perf-advisor
    chart: {{ template "yugaware.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.commonLabels }}
{{ include "yugaware.commonLabels" . | indent 4 }}
{{- end }}
{{- if .Values.perfAdvisor.service.annotations }}
  annotations: {{ .Values.perfAdvisor.service.annotations | toYaml | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.yugaware.service.type }}
  {{- if .Values.yugaware.service.clusterIP }}
  clusterIP: {{ .Values.yugaware.service.clusterIP }}
  {{- end }}
  {{- if and (eq .Values.yugaware.service.type "LoadBalancer") (.Values.yugaware.service.ip) }}
  loadBalancerIP: {{ .Values.yugaware.service.ip }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}-perf-advisor
  ports:
    - protocol: {{ .Values.perfAdvisor.protocol }}
      name: http
      port: {{ .Values.perfAdvisor.port | default 8080 }}
      targetPort: 8080

{{- if .Values.perfAdvisor.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-perf-advisor-service-monitor
  {{- if .Values.perfAdvisor.serviceMonitor.annotations }}
  annotations:
{{ toYaml .Values.perfAdvisor.serviceMonitor.annotations | indent 4 }}
  {{- end }}
  labels:
    app: {{ .Release.Name }}-perf-advisor
    chart: {{ template "yugaware.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.commonLabels }}
{{ include "yugaware.commonLabels" . | indent 4 }}
{{- end }}
spec:
  endpoints:
    - port: http
      path: /actuator/prometheus
  selector:
    matchLabels:
      app: {{ .Release.Name }}-perf-advisor
{{- end }}

{{- end }}
