{{- if .Values.perfAdvisor.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-perf-advisor-secret
  labels:
    app: {{ .Release.Name }}-perf-advisor
    chart: {{ template "yugaware.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.commonLabels }}
{{ include "yugaware.commonLabels" . | indent 4 }}
{{- end }}
type: Opaque
data:
  PA_API_TOKEN: {{ include "getValuesOrGetOrGeneratePassword" (dict "Namespace" .Release.Namespace "Name" (printf "%s%s" .Release.Name "-perf-advisor-secret") "Key" "PA_API_TOKEN" "Kind" "secret" "Length" "64" "UserValue" .Values.perfAdvisor.api.token) | quote }}
{{- if (.Values.tls.enabled) }}
  KEYSTORE_PASSWORD: {{ include "getValuesOrGetOrGeneratePassword" (dict "Namespace" .Release.Namespace "Name" (printf "%s%s" .Release.Name "-perf-advisor-secret") "Key" "KEYSTORE_PASSWORD" "Kind" "secret" "Length" "64" "UserValue" .Values.tls.perfAdvisor.keystore.password) | quote }}
{{- end }}
{{- end }}
