{{ if and .Values.yugaware.kubernetesOperatorEnabled
     (and (not .Values.rbac.create)
          (not .Values.yugaware.serviceAccount)) }}
{{ fail "Must use rbac or provide a service account with the correct permissions if Kubernetes operator is enable " }}
{{- end }}
{{- if and .Values.yugaware.kubernetesOperatorNamespace
      (and (not .Values.yugaware.serviceAccount)
           (ne .Release.Namespace .Values.yugaware.kubernetesOperatorNamespace)
           (.Values.rbac.namespaced)) }}
{{ fail "When using operator in a specific namespace, you must either 1) provide a service account with the correct permissions or 2) deploy the operator in the same namespace with rbac.namespaced set to true, or 3) use global rbac.create without rbac.namespaced"}}
{{- end }}
{{- if and (not .Values.yugaware.kubernetesOperatorNamespace) .Values.rbac.namespaced }}
{{ fail "Cannot use the operator globally with namespaced RBAC"}}
{{- end }}
{{ if not .Values.yugaware.serviceAccount }}
{{/* Create a default service account if one is not provided */}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  labels:
    k8s-app: yugaware
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
{{- if .Values.commonLabels }}
{{ include "yugaware.commonLabels" . | indent 4 }}
{{- end }}
{{- if .Values.yugaware.serviceAccountAnnotations }}
  annotations:
{{ toYaml .Values.yugaware.serviceAccountAnnotations | indent 4 }}
{{- end }}
{{ end }}
{{- if .Values.rbac.create }}
{{- if .Values.ocpCompatibility.enabled }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-cluster-monitoring-view
  labels:
    app: yugaware
{{- if .Values.commonLabels }}
{{ include "yugaware.commonLabels" . | indent 4 }}
{{- end }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.yugaware.serviceAccount | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{/* Always create rest of the RBAC permissions when operator is enabled */}}
{{- if or (not .Values.ocpCompatibility.enabled) .Values.yugaware.kubernetesOperatorEnabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.rbac.namespaced }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
  name: {{ .Release.Name }}
  labels:
{{- if .Values.commonLabels }}
{{ include "yugaware.commonLabels" . | indent 4 }}
{{- end }}
rules:
# Set of permissions required for operator
- apiGroups:
  - operator.yugabyte.io
  resources:
  - "*"
  verbs:
  - "get"
  - "create"
  - "delete"
  - "patch"
  - "list"
  - "watch"
  - "update"
# Set of permissions required to install, upgrade, delete the yugabyte chart
- apiGroups:
  - "policy"
  resources:
  - "poddisruptionbudgets"
  verbs:
  - "get"
  - "create"
  - "delete"
  - "patch"
- apiGroups:
  - ""
  resources:
  - "services"
  verbs:
  - "get"
  - "delete"
  - "create"
  - "patch"
- apiGroups:
  - "apps"
  resources:
  - "statefulsets"
  verbs:
  - "get"
  - "list"
  - "delete"
  - "create"
  - "patch"
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "create"
  - "list"
  - "get"
  - "delete"
  - "update"
  - "patch"
- apiGroups:
  - "cert-manager.io"
  resources:
  - "certificates"
  verbs:
  - "create"
  - "delete"
  - "get"
  - "patch"
- apiGroups:
  - ""
  resources:
  - "configmaps"
  verbs:
  - "get"
  - "create"
  - "patch"
  - "delete"
# Set of permissions required by YBA to manage YB DB universes
{{- if not .Values.rbac.namespaced }}
- apiGroups:
  - ""
  resources:
  - "namespaces"
  verbs:
  - "delete"
  - "create"
  - "patch"
  - "get"
  - "list"
{{- end }}
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "get"
  - "list"
  - "delete"
  - "watch"
- apiGroups:
  - ""
  resources:
  - "services"
  verbs:
  - "get"
  - "list"
- apiGroups:
  - ""
  resources:
  - "persistentvolumeclaims"
  verbs:
  - "get"
  - "patch"
  - "list"
  - "delete"
- apiGroups:
  - ""
  resources:
  - "pods/exec"
  verbs:
  - "create"
- apiGroups:
  - "apps"
  resources:
  - "statefulsets/scale"
  verbs:
  - "patch"
- apiGroups:
  - ""
  resources:
  - "events"
  verbs:
  - "list"
# required to scrape resource metrics like CPU, memory, etc.
# required to validate zones during provider creation
# required to auto-fill the zone labels for provider creation
{{- if not .Values.rbac.namespaced }}
{{/* nodes and nodes/proxy are global resources */}}
- apiGroups:
  - ""
  resources:
  - "nodes"
  verbs:
  - "list"
  - "get"
  - "watch"
# required to scrape resource metrics like CPU, memory, etc.
- apiGroups:
  - ""
  resources:
  - "nodes/proxy"
  verbs:
  - "get"
{{- end }}
# Ref: https://github.com/yugabyte/charts/commit/4a5319972385666487a7bc2cd0c35052f2cfa4c5
- apiGroups:
  - ""
  resources:
  - "events"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete"
- apiGroups:
  - ""
  resources:
  - "configmaps"
  verbs:
  - "list"
  - "watch"
  - "update"
# required to validate storage class during provider creation and
# volume expansion
{{- if not .Values.rbac.namespaced }}
- apiGroups:
  - "storage.k8s.io"
  resources:
  - "storageclasses"
  verbs:
  - "get"
{{- end }}
# required to validate existance of issuer during provider creation.
- apiGroups:
  - "cert-manager.io"
  resources:
  - "issuers"
{{- if not .Values.rbac.namespaced }}
  - "clusterissuers"
{{- end }}
  verbs:
  - "get"
- apiGroups:
  - "opentelemetry.io"
  resources:
  - "opentelemetrycollectors"
  verbs:
  - "get"
  - "create"
  - "patch"
  - "delete"
---
{{- if .Values.rbac.namespaced }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  labels:
    k8s-app: yugaware
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
{{- if .Values.commonLabels }}
{{ include "yugaware.commonLabels" . | indent 4 }}
{{- end }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.yugaware.serviceAccount | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  {{- if .Values.rbac.namespaced }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
