# Copyright (c) YugaByte, Inc.

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-yugaware
  labels:
    app: {{ .Release.Name }}-yugaware
    chart: {{ template "yugaware.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Values.helm2Legacy | ternary "Tiller" (.Release.Service | quote) }}
spec:
  serviceName: {{ .Release.Name }}-yugaware
  replicas: {{ .Values.yugaware.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-yugaware
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configs.yaml") . | sha256sum }}
{{- if .Values.yugaware.pod.annotations }}
{{ toYaml .Values.yugaware.pod.annotations | indent 8 }}
{{- end }}
      labels:
        app: {{ .Release.Name }}-yugaware
    spec:
      serviceAccountName: {{ .Release.Name }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      {{- end }}
      volumes:
        - name: yugaware-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-yugaware-storage
        - name: yugaware-ui
          emptyDir: {}
        - name: yugaware-config
          projected:
            sources:
              - configMap:
                  name: {{ .Release.Name }}-yugaware-app-config
                  items:
                    - key: application.docker.conf
                      path: application.docker.conf
            {{- if .Values.yugaware.universe_boot_script }}
              - configMap:
                  name: {{ .Release.Name }}-universe-boot-script
                  items:
                    - key: universe_boot_script
                      path: universe-boot-script.sh
            {{- end }}
        - name: nginx-config
          configMap:
            name: {{ .Release.Name }}-yugaware-nginx-config
            items:
              - key: default.conf
                path: default.conf
        - name: nginx-main-config
          configMap:
            name: {{ .Release.Name }}-yugaware-nginx-main-config
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: prometheus-config
          configMap:
            name: {{ .Release.Name }}-yugaware-prometheus-config
            items:
              - key: prometheus.yml
                path: prometheus.yml

        {{- if .Values.tls.enabled }}
        - name: {{  .Release.Name }}-yugaware-tls-cert
          secret:
            secretName: {{ .Release.Name }}-yugaware-tls-cert
        {{- end }}
      initContainers:
        - image: {{ include "full_yugaware_image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: prometheus-configuration
          command:
            - 'bash'
            - '-c'
            - >
              cp /default_prometheus_config/prometheus.yml /prometheus_configs/prometheus.yml;
              echo "finding pem files with 660 permission";
              directory_name="/opt/yugabyte/yugaware/data";
              pemfiles=$(find "$directory_name"/keys/** -name "*.pem" -exec stat -c "%a" {} +);
              if [[ $pemfiles == *660* ]]; then
                echo "creating new key directory";
                mkdir "$directory_name"/new_keys;
                echo "copying content of data/key/* to new keys directory";
                cp -r "$directory_name"/keys/* "$directory_name"/new_keys/;
                echo "setting permission to all pem files to 600";
                find "$directory_name"/new_keys/** -name "*.pem" -exec chmod 600 {} +;
                echo "Renaming old keys directory";
                mv "$directory_name"/keys "$directory_name"/keys-"$(date +%s)";
                echo "Renaming new keys directory";
                mv "$directory_name"/new_keys "$directory_name"/keys;
              else
                echo "Does not find pem file with 660 permission";
              fi;
          {{- if .Values.securityContext.enabled }}
          securityContext: {{- omit .Values.securityContext "enabled" "fsGroup" | toYaml | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: prometheus-config
            mountPath: /default_prometheus_config
          - name: yugaware-storage
            mountPath: /prometheus_configs
            subPath: prometheus.yml
          - name: yugaware-storage
            mountPath: /opt/yugabyte/yugaware/data/
            subPath: data
      containers:
        {{ if not .Values.postgres.external.host }}
        - name: postgres
          image: {{ include "full_image" (dict "containerName" "postgres" "root" .) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-yugaware-global-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-yugaware-global-config
                  key: postgres_password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-yugaware-global-config
                  key: postgres_db
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres

         {{- if .Values.postgres.resources }}
          resources:
{{ toYaml .Values.postgres.resources | indent 12 }}
          {{ end }}

          volumeMounts:
            - name: yugaware-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres_data
        {{ end }}
        - name: prometheus
          image: {{ include "full_image" (dict "containerName" "prometheus" "root" .) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.securityContext.enabled }}
          securityContext: {{- omit .Values.securityContext "enabled" "fsGroup"  | toYaml | nindent 12 }}
          {{- else if (not .Values.ocpCompatibility.enabled) }}
          securityContext:
            runAsUser: 0
          {{- end }}

          {{- if .Values.prometheus.resources }}
          resources:
{{ toYaml .Values.prometheus.resources | indent 12 }}
          {{ end }}

          volumeMounts:
          - name: yugaware-storage
            mountPath: /prometheus_configs
            subPath: prometheus.yml
          - name: yugaware-storage
            mountPath: /prometheus/
          {{- if .Values.prometheus.scrapeNodes }}
          - name: yugaware-storage
            mountPath: /opt/yugabyte/prometheus/targets
            subPath: swamper_targets
          {{- end }}
          {{- if .Values.prometheus.evaluateAlertRules }}
          - name: yugaware-storage
            mountPath: /opt/yugabyte/prometheus/rules
            subPath: swamper_rules
          {{- end }}
          args:
            - --config.file=/prometheus_configs/prometheus.yml
            - --storage.tsdb.path=/prometheus/
            - --web.enable-admin-api
            - --web.enable-lifecycle
            - --storage.tsdb.retention.time={{ .Values.prometheus.retentionTime }}
          ports:
            - containerPort: 9090
        - name: yugaware
          image: {{ include "full_yugaware_image" . }}
          {{- if .Values.securityContext.enabled }}
          securityContext: {{- omit .Values.securityContext "enabled" "fsGroup" | toYaml | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          {{- if .Values.yugaware.resources }}
          resources:
{{ toYaml .Values.yugaware.resources | indent 12 }}
          {{- end }}

          command: [ "/sbin/tini", "--"]
          args:
            - "bin/yugaware"
            - "-Dconfig.file=/data/application.docker.conf"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-yugaware-global-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-yugaware-global-config
                  key: postgres_password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-yugaware-global-config
                  key: postgres_db
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-yugaware-global-config
                  key: app_secret
          ports:
            - containerPort: 9000
              name: yugaware
          volumeMounts:
          - name: yugaware-config
            mountPath: /data
          - name: yugaware-storage
            mountPath: /opt/yugabyte/yugaware/data/
            subPath: data
          # old path for backward compatibility
          - name: yugaware-storage
            mountPath: /opt/yugaware_data/
            subPath: data
          - name: yugaware-storage
            mountPath: /opt/yugabyte/releases/
            subPath: releases
          # old path for backward compatibility
          - name: yugaware-storage
            mountPath: /opt/releases/
            subPath: releases
          - name: yugaware-storage
            mountPath: /opt/yugabyte/prometheus/targets
            subPath: swamper_targets
          - name: yugaware-storage
            mountPath: /opt/yugabyte/prometheus/rules
            subPath: swamper_rules
          - name: yugaware-storage
            mountPath: /prometheus_configs
            subPath: prometheus.yml
        - name: nginx
          image: {{ include "full_image" (dict "containerName" "nginx" "root" .) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 8080

          {{- if .Values.nginx.resources }}
          resources:
{{ toYaml .Values.nginx.resources | indent 12 }}
          {{- end }}

          volumeMounts:
          - mountPath: /etc/nginx/conf.d/
            name: nginx-config
          - mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            name: nginx-main-config
          {{- if .Values.tls.enabled }}
          - name: {{  .Release.Name }}-yugaware-tls-cert
            mountPath: /opt/certs/
            readOnly: true
          {{- end }}
{{ if .Values.sidecars }}
{{ toYaml .Values.sidecars | indent 8 }}
{{ end }}
